using System.Collections.Frozen;

namespace Revolt.Sniff;

public sealed partial class Sniffer {

    private static readonly FrozenDictionary<ushort, string> l4ProtocolNames = new Dictionary<ushort, string>() {
        { 0,   String.Empty },
        { 1,   "TCP Port Service Multiplexer" },
        { 7,   "Echo Protocol" },
        { 9,   "Discard Protocol" },
        { 11,  "Systat" },
        { 13,  "Daytime Protocol" },
        { 17,  "QOTD - Quote of the Day" },
        { 18,  "MSP - Message Send Protocol" },
        { 19,  "CHARGEN - Character Generator Protocol " },
        { 20,  "FTP - File Transfer Protocol data transfer" },
        { 21,  "FTP - File Transfer Protocol control" },
        { 22,  "SSH - Secure Shell" },
        { 23,  "Telnet" },
        { 25,  "SMTP - Simple Mail Transfer Protocol" },
        { 37,  "Time Protocol" },
        { 42,  "Host Name Server Protocol" },
        { 43,  "WHOIS protocol" },
        { 49,  "TACACS/TACACS+" },
        { 53,  "DNS - Domain Name System" },
        { 67,  "BOOTP/DHCP client" },
        { 68,  "BOOTP/DHCP server" },
        { 69,  "TFTP - Trivial File Transfer Protocol" },
        { 70,  "Gopher" },
        { 71,  "NETRJS protocol" },
        { 72,  "NETRJS protocol" },
        { 73,  "NETRJS protocol" },
        { 74,  "NETRJS protocol" },
        { 79,  "Finger protocol" },
        { 80,  "HTTP - Hypertext Transfer Protocol" },
        { 88,  "Kerberos" },
        { 95,  "SUPDUP" },
        { 101, "NIC host name" },
        { 102, "Transport Service Access Point (TSAP" },
        { 104, "DICOM - Digital Imaging and Communications in Medicine" },
        { 105, "CCSO Nameserver" },
        { 107, "RTelnet - Remote User Telnet Service" },
        { 108, "SNA - Systems Network Architecture" },
        { 109, "POP1 - Post Office Protocol" },
        { 110, "POP3 - Post Office Protocol" },
        { 111, "ONC RPC - Open Network Computing Remote Procedure Call" },
        { 112, "McIDAS Data Transmission Protocol " },
        { 115, "Simple File Transfer Protocol" },
        { 117, "UUCP Mapping Project" },
        { 118, "SQL - Structured Query Language" },
        { 119, "NNTP - Network News Transfer Protocol" },
        { 123, "NTP - Network Time Protocol" },
        { 135, "RPC - Remote Procedure Call" },
        { 137, "NetBIOS Name Service" },
        { 138, "NetBIOS Datagram Service" },
        { 139, "NetBIOS Session Service" },
        { 143, "IMAP - Internet Message Access Protocol" },
        { 151, "EMS - Energy Management System" },
        { 152, "BFTP - Background File Transfer Program" },
        { 153, "SGMP - Simple Gateway Monitoring Protocol" },
        { 156, "SQL - Structured Query Language" },
        { 158, "DMSP - Distributed Mail System Protocol" },
        { 161, "SNMP - Simple Network Management Protocol" },
        { 162, "SNMPTRAP - Simple Network Management Protocol Trap" },
        { 170, "PostScript print server" },
        { 177, "XDMCP - X Display Manager Control Protocol" },
        { 179, "BGP - Border Gateway Protocol" },
        { 194, "IRC - Internet Relay Chat" },
        { 199, "SMUX - Unix Multiplexer" },
        { 201, "AppleTalk" },
        { 209, "Quick Mail Transfer Protocol" },
        { 210, "ANSI Z39.50" },
        { 213, "IPX - Internetwork Packet Exchange" },
        { 218, "MPP - Message posting protocol" },
        { 220, "IMAP - Internet Message Access Protocol" },
        { 259, "ESRO - Efficient Short Remote Operations" },
        { 262, "Arcisdms" },
        { 264, "BGMP - Border Gateway Multicast Protocol" },
        { 308, "Novastor Online Backup " },
        { 311, "macOS Server" },
        { 318, "TSP - Time Stamp Protocol" },
        { 319, "PTP - Precision Time Protocol event messages" },
        { 320, "PTP - Precision Time Protocol general messages" },
        { 323, "Resource Public Key Infrastructure" },
        { 350, "MATIP - Mapping of Airline Traffic over Internet Protocol" },
        { 351, "MATIP type B " },
        { 366, "ODMR - On-Demand Mail Relay" },
        { 369, "Rpc2portmap" },
        { 378, "Amiga Envoy Network Inquiry Protocol" },
        { 383, "HP data alarm manager" },
        { 387, "AURP - AppleTalk Update-based Routing Protocol" },
        { 389, "LDAP - Lightweight Directory Access Protocol" },
        { 399, "Digital Equipment Corporation DECnet+" },
        { 401, "UPS - Uninterruptible power supply" },
        { 427, "SLP - Service Location Protocol" },
        { 433, "NNTP - Network News Transfer Protocol" },
        { 434, "Mobile IP Agent" },
        { 443, "HTTPS - Hypertext Transfer Protocol Secure" },
        { 444, "SNPP - Simple Network Paging Protocol" },
        { 445, "MSDS - Microsoft Directory Services" },
        { 464, "Kerberos Change/Set password" },
        { 465, "Message Submission over TLS protocol" },
        { 475, "Aladdin Knowledge Systems Hasp services" },
        { 497, "Retrospect" },
        { 500, "ISAKMP/IKE - Internet Security Association and Key Management Protocol" },
        { 502, "Modbus Protocol" },
        { 510, "Citadel" },
        { 512, "Rexec - Remote Process Execution" },
        { 513, "Who/Rlogin" },
        { 514, "Syslog" },
        { 515, "LPD - Line Printer Daemon" },
        { 517, "Talk" },
        { 518, "NTalk" },
        { 520, "RIP - Routing Information Protocol" },
        { 521, "RIP - Routing Information Protocol Next Generation " },
        { 524, "NCP - NetWare Core Protocol" },
        { 525, "Timeserver" },
        { 530, "RPC - Remote Procedure Call" },
        { 532, "netnews" },
        { 533, "netwall" },
        { 540, "UUCP - Unix-to-Unix Copy Protocol" },
        { 542, "Commerce Applications" },
        { 543, "KLogin - Kerberos login" },
        { 544, "KShell - Kerberos Remote shell" },
        { 546, "DHCPv6 client" },
        { 547, "DHCPv6 server" },
        { 548, "AFP - Apple Filing Protocol over TCP" },
        { 554, "RTSP - Real Time Streaming Protocol" },
        { 556, "RFS - Remote File Sharing" },
        { 561, "RMonitor - Remote Monitor" },
        { 563, "NNTPS - NNTP over TLS/SSL" },
        { 587, "MSA - Message Submission Agent" },
        { 591, "FileMaker" },
        { 593, "HTTP RPC" },
        { 601, "Reliable Syslog Service" },
        { 604, "TUNNEL" },
        { 623, "ASF-RMCP - ASF Remote Management and Control Protocol" },
        { 631, "IPP - Internet Printing Protocol" },
        { 636, "LDAPS - Lightweight Directory Access Protocol over TLS/SSL" },
        { 639, "MSDP - Multicast Source Discovery Protocol" },
        { 646, "LDP - Label Distribution Protocol" },
        { 647, "DHCP Failover protocol" },
        { 648, "RRP - Registry Registrar Protocol" },
        { 651, "IEEE-MMS " },
        { 654, "MMP - Media Management Protocol" },
        { 655, "Tinc VPN daemon " },
        { 657, "RMC - Remote monitoring and Control" },
        { 660, "macOS Server administration" },
        { 666, "Doom FPS" },
        { 674, "ACAP - Application Configuration Access Protocol" },
        { 684, " CORBA - Common Object Request Broker Architecture" },
        { 690, "VATP - Velneo Application Transfer Protocol" },
        { 691, "MS Exchange Routing " },
        { 694, "Linux-HA high-availability heartbeat " },
        { 695, "MMS-SSL - Media Management System over SSL" },
        { 698, "OLSR - Optimized Link State Routing " },
        { 700, "EPP - Extensible Provisioning Protocol" },
        { 701, "LMP - Link Management Protocol" },
        { 702, "IRIS - Internet Registry Information Service" },
        { 706, "SILC - Secure Internet Live Conferencing over BEEP" },
        { 711, "Cisco Tag Distribution Protocol" },
        { 712, "TBRPF - Topology Broadcast based on Reverse-Path Forwarding" },
        { 749, "Kerberos administration" },
        { 750, "Kerberos version IV " },
        { 753, "RRH - Reverse Routing Header" },
        { 754, "Tell send " },
        { 760, "KReg - Kerberos registration" },
        { 800, "MDBS-daemon" },
        { 802, "MODBUS/TCP Security" },
        { 829, "CMP - Certificate Management Protocol" },
        { 830, " NETCONF over SSH" },
        { 831, "NETCONF over BEEP" },
        { 832, "NETCONF for SOAP over HTTPS" },
        { 833, "NETCONF for SOAP over BEEP" },
        { 847, "DHCP Failover protocol" },
        { 848, "GDOI - Group Domain Of Interpretation" },
        { 853, "DNS over TLS" },
        { 860, "iSCSI" },
        { 861, "OWAMP control" },
        { 862, "TWAMP control" },
        { 873, "rsync" },
        { 888, "CDDBP - CD DataBase" },
        { 902, "VMware ESXi" },
        { 903, "VMware ESXi" },
        { 953, "RNDC - Remote Name Daemon Control" },
        { 981, "Remote HTTPS management" },
        { 989, "FTP over TLS/SSL data" },
        { 990, "FTP over TLS/SSL control" },
        { 991, "NAS - Netnews Administration System" },
        { 992, "Telnet over TLS/SSL" },
        { 993, "IMAPS - Internet Message Access Protocol over TLS/SSL" },
        { 1433, "MS-SQL - Microsoft SQL server" },
        { 2049, "NFS - Network File System" },
        { 3260, "iSCSI" },
        { 3269, "LDAP over SSL" },
        { 3389, "RDP - Remote Desktop Protocol" },
        { 3306, "MySQL" },
        { 5432, "PostgreSQL" },
        { 5500, "VNC, Virtual Network Computer" },
        { 5656, "UniFi AP-EDU broadcasting" },
        { 5657, "UniFi AP-EDU broadcasting" },
        { 5658, "UniFi AP-EDU broadcasting" },
        { 5659, "UniFi AP-EDU broadcasting" },
        { 5800, "VNC - Virtual Network Computer" },
        { 5801, "VNC - Virtual Network Computer" },
        { 5900, "VNC - Virtual Network Computer" },
        { 5901, "uVNC - Virtual Network Computer" },
        { 5902, "uVNC - Virtual Network Computer" },
        { 5903, "uVNC - Virtual Network Computer" },
        { 6666, "UniFi Camera Stream Listener" },
        { 6789, "UniFi Mobile Speed Test" },
        { 6969, "BitTorrent tracker" },
        { 7004, "UniFi UVC-Micro Talkback" },
        { 7442, "UniFi Camera Management" },
        { 7447, "UniFi RTSP, Real Time Streaming Protocol" },
        { 7680, "WUDO, Windows Update Delivery Optimization" },
        { 8080, "HTTP alternate, Hypertext Transfer Protocol" },
        { 8291, "Mikrotik RouterOS Winbox" },
        { 8443, "HTTP over TLS/SSL alternate" },
        { 8530, "WSUS, Windows Server Update Services" },
        { 8531, "WSUS, Windows Server Update Services over TLS/SSL" },
        { 8728, "Mikrotik RouterOS API" },
        { 8729, "Mikrotik RouterOS API over TLS/SSL" },
        { 9100, "Print Server" },
        { 10000,"NDMP - Network Data Management Protocol" },
        { 10001,"UniFi Discovery Service" }
    }.ToFrozenDictionary();

    public static string GetL4ProtocolName(ushort port) =>
        l4ProtocolNames.TryGetValue(port, out string name) ? name : String.Empty;

}